import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Email from "./components/icon/Email";
import Instagram from "./components/icon/Instagram";
import Linkdin from "./components/icon/Linkdin";
import Github from "./components/icon/Github";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>

          </head>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
            {children}

             <footer className="flex justify-between h-10 py-5 px-32 bg-black/20 ">
              
                <div className="flex items-center gap-5">
                    <a href="https://www.linkedin.com/in/ghazaleh-nezamghadiri-06b626302">
                        <Linkdin />
                    </a>
                    <a href="https://github.com/GhazalehNezamghadiri">
                        <Github />
                    </a>
                    <a href="mailto:ghazalehghadiri2@gmail.com">
                        <Email />
                    </a>
                    <a href="https://www.instagram.com/ghazale.ghadiri/?hl=en">
                        <Instagram />
                    </a>
                </div>
            </footer>
          </body>
        </html>
        );
}
